name: push on tag
on:
  push:
    tags:
      - *
    branches:    
      - master

jobs:
  buildPlugin:
    runs-on: ubuntu-latest
    if: github.ref == 'ref/heads/master'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - run: gradle buildPlugin
